### ISSUE TITLE
Add a link to C-ESM-EP wiki on the comparison web page

### ISSUE THREAD

**Issue by jypeter** [jservonnat/C-ESM-EP#12]
I think it would be useful (and easy) to add a link to

https://github.com/jservonnat/C-ESM-EP/wiki

from the main "Comparison" web page (don't know how [this kind of page](https://vesg.ipsl.upmc.fr/thredds/fileServer/IPSLFS/jservon/C-ESM-EP/standard_comparison_jservon/C-ESM-EP_standard_comparison.html) is called), probably at the bottom. This way, if you want to check the doc or change parameters or whatever, you can just click on the link rather than having to find your bookmarks or notes

This would also be useful to advertise C-ESM-EP

You can probably also make the top logo image clickable with a link to the wiki (but we need the explicit link at the bottom)

The _bottom zone_ could also be used to place:
* a link to a disclaimer+acknowledgement of C-ESM-EP
* an optional cell where the user can optionally specify pairs of ['text', 'link'] (in `datasets_setup.py`) to their projects, etc...

Small left Cell | (rest of the window) Right Cell
----------|------------
left justified | right justified
C-ESM-EP | user text and link1
Disclaimer | user text and link2
<empty> | user text and link NN

**Comment by jservonnat** [comment]
Thanks a lot. I've easily added the link to the top image.
We will have to talk about the bottom zone and find a way to do it.
