### ISSUE TITLE
Automatically remove trailing '/' from the run_C-ESM-EP.py parameters

### ISSUE THREAD

**Issue by jypeter** [jservonnat/C-ESM-EP#14]
Could you automatically **remove the unnecessary "/"** that we may forget by mistake when we call `python run_C-ESM-EP.py standard_comparison`.

e.g when typing `python run_C-ESM-EP.py standard_comparison/`
or `python run_C-ESM-EP.py standard_comparison/ diag/`
or `python run_C-ESM-EP.py standard_comparison diag`

I think that's why I ended up once with a double '/' in an URL (example below). I thought it would not matter, but I later got a strange side effect

https://vesg.ipsl.upmc.fr/thredds/fileServer/IPSLFS/jypmce/C-ESM-EP/PMIP4_Barcelona_0k_ref_jypmce//MainTimeSeries/atlas_MainTimeSeries_PMIP4_Barcelona_0k_ref.html

**Comment by jservonnat** [comment]
Done. You can now use 'python run_C-ESM-EP.py standard_comparison/ diag/' to run your diag.
It wasn't the reason why you had double / in the url but I've changed it on the way.
Thanks for contributing to a cleaner and more user-friendly C-ESM-EP ;).
