### ISSUE TITLE
Images of the atlas don't show in Internet Explorer (Win 7)

### ISSUE THREAD

**Issue by jypeter** [jservonnat/C-ESM-EP#15]
I have noticed by chance that when I open a comparison atlas in **IE (Windows 7)**, the **images are not displayed on the page** (including the top image on the _home_ page). If I click where there should be an image, IE asks me if I want to open or save it. If I choose to open, IE shows it in an external viewer. See screenshots below

Not sure what's wrong. The HTML code seems simple/clear enough

I thought I maybe had some filters or settings that prevented the images to be displayed in my IE, but 2 other people had the same problem in their IE. The third one was using Edge (the new IE)  on Windows 10 and the images were displayed correctly there

![atlas_home_pb_IE](https://user-images.githubusercontent.com/2785573/54763327-12be2500-4bf6-11e9-9c7e-44ea6c75240b.png)
![atlas_pb_IE](https://user-images.githubusercontent.com/2785573/54763335-1651ac00-4bf6-11e9-822a-640ffbd062bf.png)

**Comment by jservonnat** [comment]
Everything works on Chrome, Firefox and Safari. Would you mind to have a look to find a potential solution?

**Comment by jypeter** [comment]
It works on Edge, which is now the default MS browser in Windows 10
