### ISSUE TITLE
Make sure the models (and ref) in datasets_setup.py have unique 'identifiers'

### ISSUE THREAD

**Issue by jypeter** [jservonnat/C-ESM-EP#17]
@jservonnat you may remember when my models and the reference had the following definition in `datasets_setup.py` (**without** a _customname_ definition)

```
   models = [
      dict(project = 'CMIP6', root='/ccc/work/cont003/cmip6/cmip6',
           model='IPSL-CM6A-LR', experiment='midHolocene',
           frequency='monthly', clim_period='last_200Y', ts_period='full',
           realization='r1i1p1f1', version='latest',
           customname='midHolocene'
           ),
      dict(project = 'CMIP6', root='/ccc/work/cont003/cmip6/cmip6',
           model='IPSL-CM6A-LR', experiment='lig127k',
           frequency='monthly', clim_period='last_200Y', ts_period='full',
           realization='r1i1p1f1', version='latest',
           customname='lig127k'
           ),
   ]
```
```
reference = dict(project = 'CMIP6', root='/ccc/work/cont003/cmip6/cmip6',
                 model='IPSL-CM6A-LR', experiment='piControl',
                 frequency='monthly', clim_period='last_200Y',  ts_period='full',
                 realization='r1i1p1f1', version='latest',
                 customname='piControl'
                 )
```
and I got the following error in `/home/jypmce/C-ESM-EP_custom/PMIP4_Barcelona_0k_ref/MainTimeSeries/MainTimeSeries_PMIP4_Barcelona_0k_ref_C-ESM-EP.e194064`

`error    : "Order list does not match dict keys list : ['r1i1p1f1', 'r1i1p1f1']   and ['r1i1p1f1']"`

The error was apparently due to the fact that C-ESM-EP uses the value of `realization` as a default key to some operation and the keys need to be unique. We solved this problem by explicitly supplying unique keys using the `customname` parameter

You can probably write something about this in [Building my comparison part 1: datasets_setup.py and atlas subdirectories](https://github.com/jservonnat/C-ESM-EP/wiki/Building-my-comparison-part-1:-datasets_setup.py-and-atlas-subdirectories) but it may not be easy to explain

I think C-ESM-EP should catch this problem and display an helpful error message before launching the jobs. You may already call some kind of sanity check function where you could add this test

**Comment by jservonnat** [comment]
Good point. I've added a more explicit error message for MainTimeSeries, which is the atlas where this behaviour is the most problematic.
Let's see if we extend this behaviour to other mechanisms.
