### ISSUE TITLE
Add a link from analysis back to the main page

### ISSUE THREAD

**Issue by jypeter** [jservonnat/C-ESM-EP#20]
When you are on the main page (or Table of Content) of a comparison web page, you can navigate down to a specific analysis. But from an analysis, the only way to go back to the TOC is to use the back button of the browser. This is not possible if you opened directly the web page of the analysis.

So, it would be nice to have a link back to the main page. Actually, it would also be nice to have a TOC menu on each analysis page, that would allow you to navigate directly to another analysis, without having to go through the main page

@jservonnat I hope you understand what I mean, because I'm probably not using the proper names of those pages

**Comment by jservonnat** [comment]
Done. In branch pre_v2.0
