### ISSUE TITLE
Add an explicit link from C-ESM-EP github page to the C-ESM-EP wiki

### ISSUE THREAD

**Issue by jypeter** [jservonnat/C-ESM-EP#28]
If you google "C-ESM-EP", you get a link to the [C-ESM-EP github page](https://github.com/jservonnat/C-ESM-EP), with a short summary of C-ESM-EP. **Success**!

This summary should probaby **include an explicit link** to the [C-ESM-EP wiki page](https://github.com/jservonnat/C-ESM-EP/wiki) for the people who want to actually use it, but are not familiar with github and the fact that more info may be available in the _wiki_ panel

**Comment by jservonnat** [comment]
Done
