### ISSUE TITLE
setenv

### ISSUE THREAD

**Issue by mignotj** [jservonnat/C-ESM-EP#3]
source setenv_C-ESM-EP.sh needed for python set_available_period_ts_clim.py standard_comparison/

**Comment by mignotj** [comment]
fabric@ciclad-ng:~/users/jmlod/C-ESM-EP> python set_available_period_ts_clim.py standard_comparison/
Traceback (most recent call last):
  File "set_available_period_ts_clim.py", line 18, in <module>
    from CM_atlas import *
ImportError: No module named CM_atlas

**Comment by jservonnat** [comment]
f you encounter this error, simply do a:
```
source setenv_C-ESM-EP.sh
```
