### ISSUE TITLE
Broken link in "Adding new variables to an existing atlas" page

### ISSUE THREAD

**Issue by jypeter** [jservonnat/C-ESM-EP#34]
At the bottom of

[Adding new variables to an existing atlas (based on Atlas Explorer)](https://github.com/jservonnat/C-ESM-EP/wiki/Adding-new-variables-to-an-existing-atlas-(based-on-Atlas-Explorer))

you have a broken link from _adding your own diagnostic to the C-ESM-EP_. The current link points to

https://github.com/jservonnat/C-ESM-EP/wiki/Add-your-own-diagnostic-to-the-C-ESM-EP

but it should (probably) point to

https://github.com/jservonnat/C-ESM-EP/wiki/Add-your-own-diagnostic-to-the-C-ESM-EP_v2

**Comment by jservonnat** [comment]
@jypeter Fixed, thanks!
