### ISSUE TITLE
Possibility to override atlas_head_title@diagnostics_XXX.py from params_XXX.py

### ISSUE THREAD

**Issue by jypeter** [jservonnat/C-ESM-EP#40]
It could be useful to be able to specify the title of an atlas in `params_XXX.py` rather than in `atlas_head_title@diagnostics_XXX.py` in order to reduce code replication. Details of my use case below

My use case: I want to produce the `Atmosphere_Surface` atlas with **longittudes in [-180, 180] rather than the default [0, 360]**. There may be a more efficient way to do this, but this could also be used as a very basic example in [Add your own diagnostic to the C ESM EP_v2](https://github.com/jservonnat/C-ESM-EP/wiki/Add-your-own-diagnostic-to-the-C-ESM-EP_v2)

I have therefore done the following:

1. create `Atmosphere_Surface_shift/params_Atmosphere_Surface_shift.py` in my comparison directory, and define a new domain

```
$ diff Atmosphere_Surface_shift/params_Atmosphere_Surface_shift.py Atmosphere_Surface/params_Atmosphere_Surface.py
8c8
< # --             - component: Atmosphere_Surface_shift                                          - |
---
> # --             - component: Atmosphere_Surface                                                 - |
68,70c68
< #domain = {} # Default = Globe
< domain = dict(lonmin=-180, lonmax=180,
<               latmin=-90, latmax=90)
---
> domain = {}
```

2. create share/cesmep_diagnostics/diagnostics_Atmosphere_Surface_shift.py by copying diagnostics_Atmosphere_Surface.py and just changing the title

```
$ diff diagnostics_Atmosphere_Surface_shift.py diagnostics_Atmosphere_Surface.py
45c45
< atlas_head_title = "Atmosphere Surface (Shifted)"
---
> atlas_head_title = "Atmosphere Surface"
```

3. I have also changed the value of allcomponents@run_C-ESM-EP.py, so that the _shifted atmosphere link_ appears just _below the default atmosphere link_ on the home page, rather than at the end (this trick is not documented in in [Add your own diagnostic to the C ESM EP_v2](https://github.com/jservonnat/C-ESM-EP/wiki/Add-your-own-diagnostic-to-the-C-ESM-EP_v2))

```
allcomponents = ['MainTimeSeries',
...
                 'Atmosphere_Surface',
                 'Atmosphere_Surface_shift',
```

For step 2, if it was possible to set the title value in `params_Atmosphere_Surface_shift.py`, I could then **just make a symbolic link from `diagnostics_Atmosphere_Surface_shift.py` to `diagnostics_Atmosphere_Surface.py`**, and **avoid duplicating** the code of diagnostics_Atmosphere_Surface_shift.py

**Comment by jservonnat** [comment]
@jypter I took this one in my hands. Now if you get the code of C-ESM-EP v2 you will have the fix.
You can now setup atlas_head_title from the params file.
I've added a sentence on this point in the documentation.
