### ISSUE TITLE
Pb de merge , là

### ISSUE THREAD

**Issue by senesis** [jservonnat/C-ESM-EP#9]
https://github.com/jservonnat/C-ESM-EP/blob/08edcec816cb1398aca8fa47be5596e60fe1ebd4/share/cesmep_modules/CM_atlas/parallel_CM_atlas.py#L1

**Comment by jservonnat** [comment]
J'ai repoussé ma version 'officielle' qui est sur Ciclad sur la branche dev_structure_1.1, est-ce que tu peux réessayer?
